[project]
name = "integrationh25"
version = "0.1.0"
description = "Project d'intégration hiver 2025 - Cégep Limoilou"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.1.1",
    "numpy>=2.2.3",
    "torch>=2.6.0",
    "pygame>=2.6.0"
]
